global:
  smtp_from: 'demo@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'demo@gmail.com'
  smtp_auth_identity: 'demo@gmail.com'
  smtp_auth_password: 'gphyrkgelagentr'

route:
# default receiver
  receiver: admin
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 30m
  routes: 
  - match_re:
      app_type: (linux)
    receiver: company
    group_by: [category]
    routes:
    - match:
        severity: critical
      receiver: devops-team-manager
    - match:
        severity: warning
      receiver: devops-team-lead

receivers:
- name: admin
  email_configs:
  - to: 'example0@gmail.com'

- name: hashedin
  email_configs:
  - to: 'example1@gmail.com'

- name: devops-team-manager
  email_configs:
  - to: 'example2@gmail.com'

- name: devops-team-lead
  email_configs:
  - to: 'example3@gmail.com'
  
  
